site_name: Maira Docs
site_url: https://maira.io
# nav:
#  - Home: index.md
#  - About: about.md
theme:
  name: material
  custom_dir: overrides
  logo: img/maira-icon.png
  favicon: img/maira-icon.png
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/maira-io

extra_css:
  - stylesheets/extra.css
